# Custom Language File for Launcher Customizer

[ejs.app]
title = "ASTRA Launcher"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "https://github.com/fourgod44/AstraLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/6zWCHNRdua"

[ejs.settings]
sourceGithubLink = "https://github.com/fourgod44/AstraLauncher"
supportLink = "https://github.com/fourgod44/AstraLauncher/issues"

[ejs.welcome]
welcomeHeader = "ASTRA Launcher"
welcomeDescription = " "
welcomeDescCTA = " "
