# Custom Language File for Launcher Customizer

[ejs.app]
title = "ASTRA Launcher"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "https://github.com/fourgod44/AstraLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@%EA%B5%B0%EC%9D%B8%EC%93%B0"
mediaDiscordURL = "https://discord.gg/q93YJ74pQU"

[ejs.settings]
sourceGithubLink = "https://github.com/fourgod44/AstraLauncher"
supportLink = "https://github.com/fourgod44/AstraLauncher/issues"

[ejs.welcome]
welcomeHeader = "ASTRA Launcher"
welcomeDescription = " "
welcomeDescCTA = " "
